### ISSUE TITLE
receive button looks like download

### ISSUE THREAD

**Issue by VicVibesPL** [badger-cash/cashtab#1]
This button feels odd here, it's a universal download button and it will be confusing to users.  

![image](https://user-images.githubusercontent.com/11517372/194483839-37f8ab4d-d0a6-4f49-ae26-ed0f7b3b3ce0.png)

Just saying, good looking wallet UI though.

**Comment by vinarmani** [comment]
Your screenshot is not from our project. Your screenshot is from the BitcoinABC fork of CashTab

[https://github.com/Bitcoin-ABC/bitcoin-abc/tree/master/web/cashtab](https://github.com/Bitcoin-ABC/bitcoin-abc/tree/master/web/cashtab)
